export enum CommunityCategory {
  TECHNOLOGY = "TECHNOLOGY",
  GAMING = "GAMING",
  SPORTS = "SPORTS",
  ENTERTAINMENT = "ENTERTAINMENT",
  MUSIC = "MUSIC",
  ART = "ART",
  FOOD = "FOOD",
  TRAVEL = "TRAVEL",
  BUSINESS = "BUSINESS",
  HEALTH = "HEALTH",
  EDUCATION = "EDUCATION",
  SCIENCE = "SCIENCE",
}
