const CommunityTypes = [
  { label: "Technology", value: "TECHNOLOGY" },
  { label: "Gaming", value: "GAMING" },
  { label: "Sports", value: "SPORTS" },
  { label: "Entertainment", value: "ENTERTAINMENT" },
  { label: "Music", value: "MUSIC" },
  { label: "Art", value: "ART" },
  { label: "Food", value: "FOOD" },
  { label: "Travel", value: "TRAVEL" },
  { label: "Business", value: "BUSINESS" },
  { label: "Health", value: "HEALTH" },
  { label: "Education", value: "EDUCATION" },
  { label: "Science", value: "SCIENCE" },
  { label: "Programming Languages", value: "PROGRAMMING LANGUAGES" },
  {
    label: "Algorithms and Data Structures",
    value: "ALGORITHMS AND DATA STRUCTURES",
  },
  {
    label: "Computer Networks and Security",
    value: "COMPUTER NETWORKS AND SECURITY",
  },
  {
    label: "Artificial Intelligence & Machine Learning",
    value: "ARTIFICIAL INTELLIGENCE & MACHINE LEARNING",
  },
  { label: "Web Development", value: "WEB DEVELOPMENT" },
  { label: "Mobile App Development", value: "MOBILE APP DEVELOPMENT" },
  { label: "Cloud Computing", value: "CLOUD COMPUTING" },
  { label: "Operating Systems", value: "OPERATING SYSTEMS" },
  { label: "Competitive Programming", value: "COMPETITIVE PROGRAMMING" },
  { label: "Interview Preparation", value: "INTERVIEW PREPARATION" },
  { label: "Open Source Contributions", value: "OPEN SOURCE CONTRIBUTIONS" },
  {
    label: "Hackathons & Coding Challenges",
    value: "HACKATHONS & CODING CHALLENGES",
  },
  { label: "Freelancing & Remote Work", value: "FREELANCING & REMOTE WORK" },
  {
    label: "Tech Blogging & Content Creation",
    value: "TECH BLOGGING & CONTENT CREATION",
  },
  { label: "Game Development", value: "GAME DEVELOPMENT" },
  {
    label: "Cybersecurity & Ethical Hacking",
    value: "CYBERSECURITY & ETHICAL HACKING",
  },
  { label: "Blockchain & Web3", value: "BLOCKCHAIN & WEB3" },
  { label: "DevOps & Automation", value: "DEVOPS & AUTOMATION" },
  { label: "Data Science & Big Data", value: "DATA SCIENCE & BIG DATA" },
  { label: "Quantum Computing", value: "QUANTUM COMPUTING" },
  { label: "Tech Memes & Jokes", value: "TECH MEMES & JOKES" },
  { label: "Study Buddies", value: "STUDY BUDDIES" },
  {
    label: "Side Projects & Collaboration",
    value: "SIDE PROJECTS & COLLABORATION",
  },
  { label: "CS Events & Conferences", value: "CS EVENTS & CONFERENCES" },
  { label: "CS Student Support Group", value: "CS STUDENT SUPPORT GROUP" },
  { label: "Marketing", value: "MARKETING" },
  { label: "Supply Chain Management", value: "SUPPLY CHAIN MANAGEMENT" },
  { label: "International Trade", value: "INTERNATIONAL TRADE" },
  { label: "E-Commerce", value: "E-COMMERCE" },
  { label: "Business Analytics", value: "BUSINESS ANALYTICS" },
  { label: "Entrepreneurship", value: "ENTREPRENEURSHIP" },
  { label: "Retail Management", value: "RETAIL MANAGEMENT" },
  { label: "Consumer Behavior", value: "CONSUMER BEHAVIOR" },
  { label: "Financial Accounting", value: "FINANCIAL ACCOUNTING" },
  { label: "Managerial Accounting", value: "MANAGERIAL ACCOUNTING" },
  { label: "Auditing", value: "AUDITING" },
  { label: "Taxation", value: "TAXATION" },
  { label: "Corporate Finance", value: "CORPORATE FINANCE" },
  { label: "Investment Banking", value: "INVESTMENT BANKING" },
  { label: "Stock Market Trading", value: "STOCK MARKET TRADING" },
  { label: "Personal Finance", value: "PERSONAL FINANCE" },
  { label: "Financial Analysis", value: "FINANCIAL ANALYSIS" },
  { label: "Risk Management", value: "RISK MANAGEMENT" },
  { label: "Literature", value: "LITERATURE" },
  { label: "Creative Writing", value: "CREATIVE WRITING" },
  { label: "Academic Writing", value: "ACADEMIC WRITING" },
  { label: "Linguistics", value: "LINGUISTICS" },
  { label: "Grammar and Vocabulary", value: "GRAMMAR AND VOCABULARY" },
  { label: "Public Speaking", value: "PUBLIC SPEAKING" },
  { label: "Debate and Discussion", value: "DEBATE AND DISCUSSION" },
  { label: "Poetry", value: "POETRY" },
  { label: "Journalism", value: "JOURNALISM" },
  { label: "Criminal Law", value: "CRIMINAL LAW" },
  { label: "Civil Law", value: "CIVIL LAW" },
  { label: "Corporate Law", value: "CORPORATE LAW" },
  { label: "Intellectual Property Law", value: "INTELLECTUAL PROPERTY LAW" },
  { label: "International Law", value: "INTERNATIONAL LAW" },
  { label: "Human Rights Law", value: "HUMAN RIGHTS LAW" },
  { label: "Environmental Law", value: "ENVIRONMENTAL LAW" },
  { label: "Legal Research", value: "LEGAL RESEARCH" },
  { label: "Moot Court", value: "MOOT COURT" },
  { label: "Case Study Discussions", value: "CASE STUDY DISCUSSIONS" },
  { label: "Business Management", value: "BUSINESS MANAGEMENT" },
  { label: "Organizational Behavior", value: "ORGANIZATIONAL BEHAVIOR" },
  { label: "Human Resource Management", value: "HUMAN RESOURCE MANAGEMENT" },
  { label: "Marketing Management", value: "MARKETING MANAGEMENT" },
  { label: "Financial Management", value: "FINANCIAL MANAGEMENT" },
  { label: "Operations Management", value: "OPERATIONS MANAGEMENT" },
  { label: "Strategic Management", value: "STRATEGIC MANAGEMENT" },
  { label: "Business Ethics", value: "BUSINESS ETHICS" },
  { label: "Leadership Skills", value: "LEADERSHIP SKILLS" },
  { label: "Startup and Innovation", value: "STARTUP AND INNOVATION" },
];

export default CommunityTypes;
